#!/usr/bin/env python3

import datetime
import urllib.request

name = input("Что скачиваем: Ветер-1; давление-2?  ")
if name == 1:
	name = "WndDir"
else:
	name = "PresSt"

ny_2016 = datetime.date(2016,10,1) # создали дату: 1 cентября 2016 года
delta = datetime.timedelta(days=1) # дельта в 1 дня
now_date = ny_2016
part1 = "http://cliware.meteo.ru/webchart/timeser/27612/SYNOPRUS/"
part2 = "/4800/2880?colors=255,255,255;255,255,255;255,255,255;255,255,255;255,255,255;0,0,0;255,255,255&dates="
while now_date < datetime.date.today():
	date1 = now_date
	now_date = now_date + delta # Узнаем какое число будет через 1 день
	date2 = now_date
	url =  part1 + name + part2 + date1.strftime("%Y-%m-%d") + "," + date2.strftime("%Y-%m-%d")
	img = urllib.request.urlopen(url).read()
	out = open(date1.strftime("%Y-%m-%d") + "," + date2.strftime("%Y-%m-%d") +".jpg", "wb")
	out.write(img)
	out.close	
	
	

